### ISSUE TITLE
feat: remove usage of SharedPref on patches

### ISSUE THREAD

**Issue by Canny1913** [revanced/revanced-integrations#97] opened 2022-07-23 20:03 UTC
## 🐞 Issue

Because SettingsPatch doesnt exist yet, some patches like `default-quality-patch` rely on SharedPrefs to function properly.

## ❗ Solution

Switch to using SettingsPatch once it's functional.

**Comment by TheJeterLP** [comment] 2022-07-28 14:14
Dupe of 
- https://github.com/revanced/revanced-patches/issues/158

**Closed by TheJeterLP** 2022-07-28 14:14 UTC
Labels: feature-request
