### ISSUE TITLE
back button not working please fix it

### ISSUE THREAD

**Issue by GHD95** [revanced/revanced-integrations#159] opened 2022-09-26 15:00 UTC
### Type

Cosmetic

### Bug description

back button not working please fix it

### Steps to reproduce

Please fix this difficult error.

### Relevant log output

```shell
Let's fix it
```

### Screenshots or videos

Uploading screen-20220926-215842.mp4…

### Solution

No description available

### Additional context

No description availablehttps://user-images.githubusercontent.com/71612380/192312374-131e7010-df15-4fff-a403-955fb108d05b.mp4

**Comment by GHD95** [comment] 2022-09-26 15:01
Uploading screen-20220926-215842.mp4…

**Comment by GHD95** [comment] 2022-09-26 15:03
Uploading screen-20220926-215842.mp4

**Comment by oSumAtrIX** [comment] 2022-09-26 16:43
Dupe of existing issue.

**Closed by oSumAtrIX** 2022-09-26 16:43 UTC
Labels: bug

**Comment by GHD95** [comment] 2022-09-26 16:50
Uploading screen-20220926-215842.mp4 please fix it, i mentioned this problem but it's not fixed for a long time
