### ISSUE TITLE
Sponsorblock Patch showing placeholder in toast notification

### ISSUE THREAD

**Issue by AroPix** [revanced/revanced-integrations#94] opened 2022-07-21 23:36 UTC
Basically, when a segment is skipped by the sponsorblock patch, it only shows a placeholder. I tried both german and english.
![Screenshot_2022-07-22-01-27-54-480_com google android youtube](https://user-images.githubusercontent.com/57004660/180332057-22d584a0-13c3-4760-99df-8c4cf7701a23.jpg)

**Comment by oSumAtrIX** [comment] 2022-07-21 23:39
Dupe of https://github.com/revanced/revanced-patches/issues/209

**Closed by oSumAtrIX** 2022-07-21 23:39 UTC
